# Generated by Django 5.1 on 2024-08-22 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текстовое поле')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='library.book', verbose_name='книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'default_related_name': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer', models.CharField(blank=True, max_length=100, null=True, verbose_name='предложение')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата и время предложения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'default_related_name': 'offers',
            },
        ),
    ]
