# Generated by Django 5.1 on 2024-08-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_title'),
        ('library', '0004_alter_ownership_book_alter_ownership_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='library.book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(editable=False, verbose_name='текстовое поле'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='предложение'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
